//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//



using System;

public class Job {
    
    private long jobIdField;
    
    private string jobNameField;
    
    private string jobDescriptionField;
    
    private string jobCreatedUserField;
    
    private System.DateTime jobCreatedDateTimeField;
    
    private string jobUpdatedUserField;
    
    private System.DateTime? jobUpdatedDateTimeField;
    
    
        public int JobId { get; set; }
    
    
        public string JobName {
        get {
            return this.jobNameField;
        }
        set {
            this.jobNameField = value;
        }
    }
    
    
        public string JobDescription {
        get {
            return this.jobDescriptionField;
        }
        set {
            this.jobDescriptionField = value;
        }
    }
    
    
        public string JobCreatedUser {
        get {
            return this.jobCreatedUserField;
        }
        set {
            this.jobCreatedUserField = value;
        }
    }
    
    
        public System.DateTime JobCreatedDateTime {
        get {
            return this.jobCreatedDateTimeField;
        }
        set {
            this.jobCreatedDateTimeField = value;
        }
    }
    
    
        public string JobUpdatedUser {
        get {
            return this.jobUpdatedUserField;
        }
        set {
            this.jobUpdatedUserField = value;
        }
    }


    public DateTime? JobUpdatedDateTime
    {
        get
        {
            return jobUpdatedDateTimeField;
        }
        set
        {
            jobUpdatedDateTimeField = value;
        }
    }
}
