//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//



public class JobGroup {
    
    private long jobGroupIdField;
    
    private object jobGroupNameField;
    
    private string jobGroupCreatedUserField;
    
    private System.DateTime jobGroupCreatedDateTimeField;
    
    private string jobGroupUpdatedUserField;
    
    private System.DateTime jobGroupUpdateDateTimeField;
    
    
        public long JobGroupId {
        get {
            return this.jobGroupIdField;
        }
        set {
            this.jobGroupIdField = value;
        }
    }
    
    
        public string JobGroupName { get; set; }
    
    
        public string JobGroupCreatedUser {
        get {
            return this.jobGroupCreatedUserField;
        }
        set {
            this.jobGroupCreatedUserField = value;
        }
    }
    
    
        public System.DateTime JobGroupCreatedDateTime {
        get {
            return this.jobGroupCreatedDateTimeField;
        }
        set {
            this.jobGroupCreatedDateTimeField = value;
        }
    }
    
    
        public string JobGroupUpdatedUser {
        get {
            return this.jobGroupUpdatedUserField;
        }
        set {
            this.jobGroupUpdatedUserField = value;
        }
    }
    
    
        public System.DateTime JobGroupUpdateDateTime {
        get {
            return this.jobGroupUpdateDateTimeField;
        }
        set {
            this.jobGroupUpdateDateTimeField = value;
        }
    }
}
