//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//



public class JobGropJobMapping {
    
    private long jobGropJobMappingIDField;
    
    private long jobGroupIdField;
    
    private long jobIdField;
    
    
        public long JobGropJobMappingID {
        get {
            return this.jobGropJobMappingIDField;
        }
        set {
            this.jobGropJobMappingIDField = value;
        }
    }
    
    
        public long JobGroupId {
        get {
            return this.jobGroupIdField;
        }
        set {
            this.jobGroupIdField = value;
        }
    }
    
    
        public long JobId {
        get {
            return this.jobIdField;
        }
        set {
            this.jobIdField = value;
        }
    }
}
