//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//



using System.ComponentModel.DataAnnotations.Schema;

public class JobProcess {
    
    private long jobProcessIdField;
    
    private long jobGroupIdField;
    
    private long jobIdField;
    
    private string jobSubmittedUserField;
    
    private System.DateTime jobSubmittedTimeField;
    
    
        public long JobProcessId { get; set; }


    [ForeignKey("JobGroupId")]
    public virtual JobGroup JobGroup { get; set; }


    [ForeignKey("JobId")]
    public virtual Job Job { get; set; }


    public string JobSubmittedUser { get; set; }


    public System.DateTime JobSubmittedTime { get; set; }
}
