//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//



using System.ComponentModel.DataAnnotations.Schema;

public class JobParameter {
    
    
    
    
        public long JobParameterId { get; set; }


    [ForeignKey("JobId")]
    public virtual Job Job { get; set; }



    public string ParamterName { get; set; }
    
    
        public string JobParamterDefaultValue { get; set; }


    public string JobParamterCreateUser { get; set; }


    public System.DateTime JobParameterCreateDateTime { get; set; }


    public string JobParamterUpdatedUser { get; set; }


    public System.DateTime JobParamterUpdatedDateTime { get; set; }
}
